language: go

go:
  - 1.8

before_script:
 - go get github.com/mitchellh/gox

script:
 - go vet *.go
 - go vet api/*.go
 - go build

after_success:
 - gox -osarch="linux/amd64" && echo $TRAVIS_TEST_RESULT
